SRC1=part1.lua
SRC2=part2.lua

.PHONY: run-example
run1-example:
	cat input-example.txt | lua $(SRC1)

.PHONY: run
run1:
	cat input.txt | lua $(SRC1)

.PHONY: run-example
run2-example:
	cat input-example.txt | lua $(SRC2)

.PHONY: run
run2:
	cat input.txt | lua $(SRC2)
